# install curl
- name: download and unarchive curl
  unarchive:
    src: https://curl.haxx.se/download/curl-{{ curl_version }}.tar.gz
    dest: /usr/local/src
    remote_src: yes

# make build
- make:
    chdir: /usr/local/src/curl-{{ curl_version }}
    target: all
    params:
      prefix: /usr/local/share/curl-{{ curl_version }}
      enable-libcurl-option: yes

# make install
- make:
    chdir: /usr/local/src/curl-{{ curl_version }}
    target: install
    params:
      prefix: /usr/local/share/curl-{{ curl_version }}
      enable-libcurl-option: yes

# create symbolic link except curl version
- name: symbolic link to curl
  file:
    src: /usr/local/share/curl-{{ curl_version }}
    dest: /usr/local/share/curl
    state: link
    force: yes

# activate curl command
- name: activate curl command
  file:
    src: /usr/local/share/curl/bin/curl
    dest: /usr/local/bin/curl
    state: link
